services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./green_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  green_taxi_ingest:
    build: 
      context: .
      dockerfile: Dockerfile
    image: green_taxi_ingest:v001
    volumes:
      - ./:/app
    command: 
      [
        "--user=root",
        "--password=root",
        "--host=pgdatabase",
        "--port=5432",
        "--db=ny_taxi",
        "--table_name=green_taxi_trips",
        "--url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz"
      ]
    depends_on:
      - pgdatabase